export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILED = "AUTH_USER_FAILED";
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";

export const ADD_EVENT = "ADD_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const GET_USER_LIST = "GET_USER_LIST";
export const GEt_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";

export const ADD_NEW_MEETING ="ADD_NEW_MEETING"
export const ADD_NEW_MEETING_SUCCESS="ADD_NEW_MEETING_SUCCESS"; 

export const GET_ALL_MEETINGS_PENDING="GET_ALL_PENDING_MEETINGS"; 
export const GET_ALL_MEETINGS_PENDING_SUCCESS="GET_ALL_MEETINGS_PENDING_SUCCESS"; 

export const GET_ALL_MEETINGS_ACCEPTED="GET_ALL_MEETINGS_ACCEPTED"; 
export const GET_ALL_MEETINGS_ACCEPTED_SUCCESS="GET_ALL_MEETINGS_ACCEPTED_SUCCESS"; 